# Generated by Django 5.2.1 on 2025-05-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_user_company'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('InvoiceNumber',), name='unique_invoice_number'),
        ),
    ]
