# Generated by Django 5.2.1 on 2025-05-16 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_invoice_unique_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='VATNo',
            field=models.IntegerField(default=0, max_length=9),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('ExpenseId', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('payment_paid', models.BooleanField(default=True)),
                ('from_Name', models.CharField(max_length=200)),
                ('from_PAN', models.IntegerField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount_Percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Taxable_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VAT_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Remarks', models.CharField(blank=True, max_length=600)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HS_Code', models.CharField(blank=True, default='-', max_length=50)),
                ('Name', models.CharField(max_length=200)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Unit', models.CharField(max_length=50)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='API.expense')),
            ],
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('ExpenseId',), name='unique_ExpenseId'),
        ),
    ]
