# Generated by Django 5.2.1 on 2025-05-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_company_vatno_expense_expenseitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='VATNo',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
