# Generated by Django 5.2.1 on 2025-05-16 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_remove_company_id_alter_company_vatno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='from_PAN',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExpenseItems', to='API.expense'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='to_PAN',
            field=models.CharField(max_length=9),
        ),
    ]
