# Generated by Django 5.2 on 2025-04-14 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('to_Name', models.TextField(max_length=200)),
                ('from_PAN', models.IntegerField()),
                ('from_Name', models.TextField(max_length=200)),
                ('to_PAN', models.IntegerField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Discount_Percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Taxable_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VAT_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Remarks', models.TextField(blank=True, max_length=600)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HS_Code', models.TextField(blank=True, default='-', max_length=50)),
                ('Name', models.TextField(max_length=200)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Unit', models.TextField(max_length=50)),
                ('Rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Items', to='API.invoice')),
            ],
        ),
    ]
