# Generated by Django 5.2 on 2025-05-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_expense_expenseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_paid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='to_address',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(),
        ),
    ]
